# Local Docker Deploy
services:
  # mongo container
  mongo:
    # TODO: Add "docker pull mongo" before runner.py to README.md
    image: mongo
    container_name: mongodb
    restart: always
    env_file: ../backend/.env
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db

  # backend container
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - backend-data:/app/data
    env_file:
      - .env.prod
    environment: # Environment variables
      - NODE_ENV=production
      - MONGO_SERVICE=mongodb
    depends_on:
      - mongo

  frontend:
    build:
      context: ../.
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    environment: # Environment variables
      - NODE_ENV=production
    volumes:
      - ../frontend:/app
      - ../shared:/shared
    depends_on:
      - backend

volumes:
  mongo-data:
    driver: local
  backend-data:
