# Docker deploy
services:
  # mongo container
  mongo:
    # TODO: Add "docker pull mongo" before runner.py to README.md
    image: mongo
    container_name: mongodb
    restart: always
    env_file: ../backend/.env
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-data:/data/db

  # backend container
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: backend
    environment: # Environment variables
      - NODE_ENV=production
      - MONGO_SERVICE=mongodb
    image: idoshahar/tahash-backend:v0.1
    ports:
      - "3000:3000"
    volumes:
      - backend-data:/app/data
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build:
      context: ../.
      dockerfile: frontend/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    environment: # Environment variables
      - NODE_ENV=production
    image: idoshahar/tahash-frontend:v0.1
    container_name: frontend
    ports:
      - "3002:8080"
    volumes:
      - ../frontend:/app
      - ../shared:/shared
    depends_on:
      - backend

volumes:
  mongo-data:
    driver: local
  backend-data:
